# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

# Points to the root of Google Test, relative to where this file is.
# Remember to tweak this if you move this file.
GTEST_DIR = googletest

# Where to find user code.
USER_DIR = .

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $(GTEST_DIR)/include

# Combine with gcov
GCOVFLAGS += -fprofile-arcs -ftest-coverage

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -pthread

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = triangle_test nextdate_test commission_test
PATHTESTS = triangle_test_c0 triangle_test_c1

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS)

clean :
	rm -f $(TESTS) $(PATHTESTS) gtest.a gtest_main.a *.o *.gcno *.gcda *.gcov

# Builds gtest.a and gtest_main.a.

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized.  This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

# Builds a sample test.  A test should link with either gtest.a or
# gtest_main.a, depending on whether it defines its own main()
# function.

triangle.o : $(USER_DIR)/triangle.cpp $(USER_DIR)/triangle.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -c $(USER_DIR)/triangle.cpp

triangle_test.o : $(USER_DIR)/triangle_test.cpp \
                     $(USER_DIR)/triangle.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/triangle_test.cpp

triangle_test : triangle.o triangle_test.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -lpthread $^ -o $@


nextdate.o : $(USER_DIR)/nextdate.cpp $(USER_DIR)/nextdate.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -c $(USER_DIR)/nextdate.cpp

nextdate_test.o : $(USER_DIR)/nextdate_test.cpp \
                     $(USER_DIR)/nextdate.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/nextdate_test.cpp

nextdate_test : nextdate.o nextdate_test.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -lpthread $^ -o $@


commission.o : $(USER_DIR)/commission.cpp $(USER_DIR)/commission.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -c $(USER_DIR)/commission.cpp

commission_test.o : $(USER_DIR)/commission_test.cpp \
                     $(USER_DIR)/commission.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/commission_test.cpp

commission_test : commission.o commission_test.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -lpthread $^ -o $@

test : triangle_test nextdate_test commission_test 
	./triangle_test
	./nextdate_test
	./commission_test

gcov : triangle_test nextdate_test commission_test 
	gcov triangle.gcno
	gcov nextdate.gcno
	gcov commission.gcno

############### path test ###################################
triangle_test_c0.o : $(USER_DIR)/triangle_test_c0.cpp \
                     $(USER_DIR)/triangle.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/triangle_test_c0.cpp

triangle_test_c0 : triangle.o triangle_test_c0.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -lpthread $^ -o $@

triangle_test_c1.o : $(USER_DIR)/triangle_test_c1.cpp \
                     $(USER_DIR)/triangle.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/triangle_test_c1.cpp

triangle_test_c1 : triangle.o triangle_test_c1.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -lpthread $^ -o $@

triangle_test_mcdc.o : $(USER_DIR)/triangle_test_mcdc.cpp \
                     $(USER_DIR)/triangle.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(USER_DIR)/triangle_test_mcdc.cpp

triangle_test_mcdc : triangle.o triangle_test_mcdc.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOVFLAGS) -lpthread $^ -o $@

pathtest: triangle_test_c0 triangle_test_c1 triangle_test_mcdc
	./triangle_test_c0
	gcov triangle.gcno
	./triangle_test_c1
	gcov -b triangle.gcno
	./triangle_test_mcdc
	gcov -b triangle.gcno
